### ISSUE TITLE
getting error in action,py

### ISSUE THREAD

**Issue by iamgsshetty** [varunsh20/Chatbot-using-rasa#2]
asyncio  - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "c:\users\gaura\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\gaura\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2021-10-18 22:04:57 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_current_price'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "c:\users\gaura\appdata\local\programs\python\python38\lib\site-packages\rasa\core\processor.py", line 772, in _run_action
    events = await action.run(
  File "c:\users\gaura\appdata\local\programs\python\python38\lib\site-packages\rasa\core\actions\action.py", line 672, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_current_price' because no endpoint is configured to run this custom action. Please take a look at the docs and set an endpoint configuration via the --endpoints flag. https://rasa.com/docs/rasa/custom-actions

**Comment by iamgsshetty** [comment]
2021-10-18 22:15:27 ERROR    rasa.core.actions.action  - Failed to run custom action 'action_current_price'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:default [The remote computer refused the network connection]
